# Cart request
GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW5AYWRtaW4uY29t.FFT3yptbtZFboDb4o6JkdoadUjNByKQnGgS3jcgMP5g

###

GET http://localhost:3000/cart/0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW5AYWRtaW4uY29t.FFT3yptbtZFboDb4o6JkdoadUjNByKQnGgS3jcgMP5g

###

POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW5AYWRtaW4uY29t.FFT3yptbtZFboDb4o6JkdoadUjNByKQnGgS3jcgMP5g

{
  "username": "admin@admin.com"
}

###

# Login request
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin@admin.com",
  "password": "admin1234"
}
